# Generated by Django 3.1.1 on 2020-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivEnc', '0003_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_value', models.CharField(max_length=15)),
                ('Port_value', models.IntegerField()),
                ('Sleep_value', models.IntegerField(default=1000)),
                ('Payload_value', models.CharField(choices=[('meterpreter/bind_tcp', 'meterpreter/bind_tcp'), ('meterpreter/reverse_tcp', 'meterpreter/reverse_tcp')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='IP',
        ),
        migrations.DeleteModel(
            name='Payload',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='Sleep',
        ),
    ]
