# Generated by Django 3.1.1 on 2020-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivEnc', '0004_auto_20200921_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Payload_value',
            field=models.CharField(choices=[('meterpreter/bind_tcp', 'meterpreter/bind_tcp'), ('meterpreter/reverse_tcp', 'meterpreter/reverse_tcp')], max_length=50),
        ),
    ]
