# Generated by Django 3.1.1 on 2020-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivEnc', '0007_auto_20200921_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='IP_value',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='Payload_value',
            field=models.CharField(choices=[('meterpreter/bind_tcp', 'meterpreter/bind_tcp'), ('meterpreter/reverse_tcp', 'meterpreter/reverse_tcp')], default='meterpreter/reverse_tcp', max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='Port_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='Sleep_value',
            field=models.IntegerField(default=1000),
        ),
    ]
