# Generated by Django 3.1.1 on 2020-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivEnc', '0011_auto_20200921_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Application_value',
            field=models.CharField(choices=[('Console Application', 'Console Application'), ('Windows Form Application', 'Windows Form Application')], default='Console Application', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Encryption_value',
            field=models.CharField(choices=[('AES-CBC', 'AES-CBC'), ('Blowfish', 'Blowfish'), ('RSA', 'RSA')], default='RSA', max_length=50, null=True),
        ),
    ]
